# Numpy Array Operations:

In [1]:
import numpy as np 

# Array Slicing 

In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing:", arr[2:7])
print("With Step:",arr[1:8:2])
print("Negative Indexing:",arr[-3])

Basic Slicing: [3 4 5 6 7]
With Step: [2 4 6 8]
Negative Indexing: 8


# For 2 Dimensional Matrix 

In [19]:
arr_2d = np.array([[2,2,3],
                   [9,0,7],
                   [7,8,4]])
print("Specific Element Array:\n", arr_2d[0,2])
print("Entire Row:\n", arr_2d[1])
print("Entire Column:\n", arr_2d[:,2]) 


Specific Element Array:
 3
Entire Row:
 [9 0 7]
Entire Column:
 [3 7 4]


# Sorting

In [23]:
unsorted = np.array([9,8,6,5,4,2,1,7,3])
print("Sorted Array:", np.sort(unsorted))

# 2 Dimensional Array Sorting 
unsorted_2 = np.array([[3,1],[2,1],[1,2]])
print("2D Sorting:\n", np.sort(unsorted_2,axis=0)) # axis= 0 for column and axis= 1 for rows

Sorted Array: [1 2 3 4 5 6 7 8 9]
2D Sorting:
 [[1 1]
 [2 1]
 [3 2]]


# Filters

In [24]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10]) 
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers:", even_numbers)

Even Numbers: [ 2  4  6  8 10]


# Filter With Mask 

In [26]:
mask = numbers > 5
print("Numbers Greater Than 5:", numbers[mask])

Numbers Greater Than 5: [ 6  7  8  9 10]


# Fancy Indexing VS np.where()

In [31]:
# Fancy
indices = [0,2,4]
print(numbers[indices])

# np.where()
where_result = np.where(numbers > 5) # np.where only prints if the condition is true 
print("Np Where:", numbers[where_result])

[1 3 5]
Np Where: [ 6  7  8  9 10]


# Conditional Arrays:

In [37]:
condition = np.array([1,2,3,4,5,6,7,8,9,10])
condition = np.where(numbers > 5, numbers * 2, numbers) # <numbers > 5 Is A Condition> <Numbers * 2: If The Number Is Greater Than 5 Multiply By 2> 
print("Conditional Array:\n", condition)                # <numbers : If The Number Is Smaller Than 5 Or Equal To Print The Number As It Is >
                                                        # As We Can See The Output The Numbers Which Were Smaller Or Equal To 5 Came As It Is in Output
                                                        # Whereas The Numbers Greater Than 5 Are Multiplied By 2 Similar To: If Else Condition  

Conditional Array:
 [ 1  2  3  4  5 12 14 16 18 20]


# Adding And Removing Data In Arrays:

In [39]:
# Merging Two Arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combine = np.concatenate((arr1,arr2))
print(combine) 

[1 2 3 4 5 6]


# Compatibility Shapes

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10]) 
print("Compatibility Status\n" "a is equal to b:",a.shape==b.shape)
print("Compatibility Status\n" "a is equal to c:",a.shape==c.shape) # The Answer In Boolean Form 



Compatibility Status
a is equal to b: True
Compatibility Status
a is equal to c: False
[[1 2]
 [3 4]
 [5 6]]


In [50]:
# Adding Rows And Column In Existing Array 

v = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((v, new_row))  # np.vstack only add rows 
print(with_new_row)
 
new_col = np.array([[9],[8]])
with_new_col = np.hstack((v,new_col)) # np.hstack add only columns 
print("New Column Added:\n", with_new_col) 

[[1 2]
 [3 4]
 [5 6]]
New Column Added:
 [[1 2 9]
 [3 4 8]]
