# Numpy Array And Basics 
Learing About Numpy

In [2]:
import numpy as np

# Creating Array From List

In [4]:
arr_1d = np.array([1,2,3,4,5])
print("1D Array:",arr_1d) 

arr_2d = np.array([[4,7,9],[9,0,8]])
print("2D Array:",arr_2d)

1D Array: [1 2 3 4 5]
2D Array: [[4 7 9]
 [9 0 8]]


# List Vs Numpy


In [27]:
py_list = [1,2,3]
print("Python List Multiplication:", py_list * 2) 

np_array = np.array([1,2,3]) # Element Wise Multiplication 
print("Python Array Multiplication:", np_array * 2) 

import time

start = time.time()
py_list = [i*2 for i in range (1000000)]
print("\n List Operation Time: ", time.time() - start) 

start = time.time()
np_array = np.arange(1000000)*2
print("\n Array Operation Time:", time.time() - start)

Python List Multiplication: [1, 2, 3, 1, 2, 3]
Python Array Multiplication: [2 4 6]

 List Operation Time:  0.06653070449829102

 Array Operation Time: 0.004207134246826172


# Creating Zeros Array

In [38]:
zeros = np.zeros((3,4)) 
print("Zeros Array:\n",zeros)

ones = np.ones((5,5))
print("Ones Array: \n", ones)

# Now For A Array With Constant Number

full = np.full((2,3),7)
print("Full Array: \n",full)

# Now For Random Arrays 
random = np.random.random((2,2))
print("Random Array: \n",random)

# Now For Sequence Array
sequence = np.arange(0,11,2)
print("Sequence Array:\n", sequence)


Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full Array: 
 [[7 7 7]
 [7 7 7]]
Random Array: 
 [[0.09441802 0.03361708]
 [0.70120182 0.52710266]]
Sequence Array:
 [ 0  2  4  6  8 10]


# Vector, Matrix And Tensor 

In [45]:
vector = np.array([1,2,3])
print("Vector:", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix:\n",matrix) 

tensor = np.array([[[2,3],[4,5],
                    [9,8],[8,1]]])
print("Tensor:\n",tensor)

Vector: [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[2 3]
  [4 5]
  [9 8]
  [8 1]]]


# Array Properties:

In [46]:
arr = np.array([[1,2,3],
                [6,7,8]]) 
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("Data Type", arr.dtype) 

Shape: (2, 3)
Dimension: 2
Size: 6
Data Type int64


# Array Reshaping

In [ ]:
arr = np.arange(12) 
print("Orignal Array",arr) 

# Reshape Array
reshape = arr.reshape((3,4))
print("Reshaped Array:", reshape)

# Flattened Array
flattened = reshape.flatten()
print("Flattened Array:", flattened)

# Raveled Array
raveled = reshape.ravel()
print("Raveled Array:", raveled) 

# Differnece In Ravel And FLatten <Flatten:Returns The Copy Of The Array> <Ravel: Returns The Orignal Form Of Array>

# Transpose
transpose = reshape.T # TRanspose: Converts Rows Into Columns And Columns Into Rows
print("Transposed Array:\n", transpose) 


Orignal Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
