## PyTorch:

In [8]:
import torch 

In [10]:
x = torch.tensor([1,2,3,4,5]) # 1D Tensor
print(x)

tensor([1, 2, 3, 4, 5])


In [12]:
y = torch.tensor([ # 2D Tensor 
    [1,2],
    [3,4]    
])

print(y)

tensor([[1, 2],
        [3, 4]])


In [17]:
# Zeros Array
z = torch.zeros(3,2) # 3 Rows 2 Columns
print(z)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [19]:
# Ones Array
o = torch.ones(3,2) # 3 Rows 2 Columns
print(o)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [25]:
# Random Decimal Array
r = torch.rand(2,2)
print(r)

tensor([[0.2622, 0.4354],
        [0.6312, 0.1861]])


In [27]:
# Tensor Shapes 
s = torch.tensor([
    [1,2,3],
    [4,5,6]
])
print(s.shape)

torch.Size([2, 3])


In [33]:
# Indexing 
i = torch.tensor([10,20,30])
print(f'One Dimensional Indexing: \n{i[0]}')

# 2D Indexing
d = torch.tensor([
    [1,2,3],
    [4,5,6]
])
print(f'Two Dimensional Indexing: \n {d[1,2]}')

One Dimensional Indexing: 
10
Two Dimensional Indexing: 
 6


# Basic Functions:

In [34]:
# Addiction & Multiplication
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(a+b)
print(a*b)

tensor([5, 7, 9])
tensor([ 4, 10, 18])
